name: 'subwayquest'
version: '1.0.0'
config-version: 2

profile: 'subwayquest'  # Matches the main key in ~/.dbt/profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  subwayquest:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +schema: mart

on-run-end:
  - "{{ reapply_min_n_suppression() }}"